#!/usr/bin/env python3
"""
NNUE Training Module - Separated from Data Generation
Imports data, trains the NNUE model, and exports weights
Network: 780 -> 256 -> 64 -> 32 -> 1 (WASM optimized)
"""

import chess
import numpy as np
import struct
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from typing import List, Optional
import random
import os
from pathlib import Path

# ============== Configuration ==============
class Config:
    # Network architecture - WASM optimized
    NNUE_INPUT_DIM = 780
    NNUE_H1 = 256    # WASM optimized
    NNUE_H2 = 64     # Better defense
    NNUE_H3 = 32     # Small 3rd layer
    NNUE_OUT = 1
    
    # Training parameters
    BATCH_SIZE = 2048
    LEARNING_RATE = 0.001
    EPOCHS = 200
    VALIDATION_SPLIT = 0.1
    WEIGHT_DECAY = 1e-4
    GRADIENT_CLIP = 1.0
    PATIENCE = 10
    DROPOUT_RATE = 0.15
    
    # Input data file (generated by data_generator.py)
    DATA_FILE = "training_data_prod.bin"
    
    # Output files
    MODEL_FILE = "nnue_model_prod.pt"
    WEIGHTS_FILE = "nnue_weights_prod.bin"
    WASM_WEIGHTS_FILE = "nnue_weights_wasm.bin"
    BIAS_FILE = "nnue_bias.bin"  # Separate bias file
    CHECKPOINT_DIR = "checkpoints_prod"

# ============== Model ==============
class NNUEProduction(nn.Module):
    """Optimized for WASM deployment"""
    def __init__(self):
        super(NNUEProduction, self).__init__()
        self.fc1 = nn.Linear(Config.NNUE_INPUT_DIM, Config.NNUE_H1)
        self.fc2 = nn.Linear(Config.NNUE_H1, Config.NNUE_H2)
        self.fc3 = nn.Linear(Config.NNUE_H2, Config.NNUE_H3)
        self.fc4 = nn.Linear(Config.NNUE_H3, Config.NNUE_OUT)
        self.dropout = nn.Dropout(Config.DROPOUT_RATE)
        self.relu = nn.ReLU()
        self._initialize_weights()
    
    def _initialize_weights(self):
        for module in self.modules():
            if isinstance(module, nn.Linear):
                nn.init.xavier_uniform_(module.weight, gain=nn.init.calculate_gain('relu'))
                nn.init.zeros_(module.bias)
    
    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.relu(self.fc2(x))
        x = self.dropout(x)
        x = self.relu(self.fc3(x))
        x = self.fc4(x)
        return x.squeeze(-1)
    
    def export_weights_wasm(self, filepath: str):
        """Export weights in WASM-compatible format"""
        weights = {
            'w1': self.fc1.weight.detach().cpu().numpy().T,
            'b1': self.fc1.bias.detach().cpu().numpy(),
            'w2': self.fc2.weight.detach().cpu().numpy().T,
            'b2': self.fc2.bias.detach().cpu().numpy(),
            'w3': self.fc3.weight.detach().cpu().numpy().T,
            'b3': self.fc3.bias.detach().cpu().numpy(),
            'w4': self.fc4.weight.detach().cpu().numpy().T,
            'b4': self.fc4.bias.detach().cpu().numpy()
        }
        
        print("\n📊 Exporting weights for WASM:")
        total_params = 0
        for name, data in weights.items():
            print(f"  {name}: {data.shape} ({data.size:,} floats)")
            total_params += data.size
        
        # Flatten in order: w1, b1, w2, b2, w3, b3, w4, b4
        flat_weights = []
        for key in ['w1', 'b1', 'w2', 'b2', 'w3', 'b3', 'w4', 'b4']:
            flat_weights.extend(weights[key].flatten())
        
        flat_array = np.array(flat_weights, dtype=np.float32)
        flat_array.tofile(filepath)
        
        print(f"\n💾 Exported {len(flat_array):,} floats to {filepath}")
        print(f"   File size: {len(flat_array) * 4 / 1024 / 1024:.2f} MB")
        
        return flat_array
    
    def export_bias_file(self, filepath: str):
        """
        Export only the biases in a separate file for WASM.
        Order: b1, b2, b3, b4
        """
        biases = {
            'b1': self.fc1.bias.detach().cpu().numpy(),
            'b2': self.fc2.bias.detach().cpu().numpy(),
            'b3': self.fc3.bias.detach().cpu().numpy(),
            'b4': self.fc4.bias.detach().cpu().numpy()
        }
        
        print("\n📊 Exporting biases for WASM:")
        total_params = 0
        for name, data in biases.items():
            print(f"  {name}: {data.shape} ({data.size:,} floats)")
            total_params += data.size
        
        # Flatten in order: b1, b2, b3, b4
        flat_biases = []
        for key in ['b1', 'b2', 'b3', 'b4']:
            flat_biases.extend(biases[key].flatten())
        
        flat_array = np.array(flat_biases, dtype=np.float32)
        flat_array.tofile(filepath)
        
        print(f"\n💾 Exported {len(flat_array):,} floats to {filepath}")
        print(f"   File size: {len(flat_array) * 4 / 1024 / 1024:.2f} MB")
        
        return flat_array
    
    def export_weights_separate(self, weights_dir: str = "weights"):
        """
        Export each layer's weights and biases as separate files for easier WASM loading.
        """
        os.makedirs(weights_dir, exist_ok=True)
        
        layers = {
            'fc1_weight': self.fc1.weight.detach().cpu().numpy().T,
            'fc1_bias': self.fc1.bias.detach().cpu().numpy(),
            'fc2_weight': self.fc2.weight.detach().cpu().numpy().T,
            'fc2_bias': self.fc2.bias.detach().cpu().numpy(),
            'fc3_weight': self.fc3.weight.detach().cpu().numpy().T,
            'fc3_bias': self.fc3.bias.detach().cpu().numpy(),
            'fc4_weight': self.fc4.weight.detach().cpu().numpy().T,
            'fc4_bias': self.fc4.bias.detach().cpu().numpy()
        }
        
        print("\n📊 Exporting separate layer files:")
        for name, data in layers.items():
            filepath = os.path.join(weights_dir, f"{name}.bin")
            data.astype(np.float32).tofile(filepath)
            print(f"  {name}: {data.shape} -> {filepath}")

# ============== Dataset ==============
class NNUE_Dataset(Dataset):
    def __init__(self, data_file: str):
        self.features = []
        self.scores = []
        self._load_data(data_file)
    
    def _load_data(self, filename: str):
        print(f"Loading training data from {filename}...")
        with open(filename, 'rb') as f:
            magic, count = struct.unpack('4sI', f.read(8))
            if magic != b'NNUE':
                raise ValueError(f"Invalid file format")
            
            print(f"Found {count} positions")
            
            for i in range(count):
                if i % 50000 == 0 and i > 0:
                    print(f"  Loaded {i} positions...")
                
                feat_data = f.read(Config.NNUE_INPUT_DIM * 4)
                if len(feat_data) < Config.NNUE_INPUT_DIM * 4:
                    break
                
                feat = np.frombuffer(feat_data, dtype=np.float32)
                self.features.append(feat)
                score, result, tactical = struct.unpack('fff', f.read(12))
                
                # Combine scores - emphasize tactical awareness
                combined_score = score * 0.7 + tactical * 0.3
                self.scores.append(combined_score)
        
        print(f"Loaded {len(self.features)} positions")
    
    def __len__(self):
        return len(self.features)
    
    def __getitem__(self, idx):
        features = self.features[idx]
        # Data augmentation: mirror position (simplified)
        if random.random() < 0.3:
            features = self._mirror_features(features)
        
        return (torch.tensor(features, dtype=torch.float32),
                torch.tensor(self.scores[idx], dtype=torch.float32))
    
    def _mirror_features(self, features: np.ndarray) -> np.ndarray:
        """Mirror the board (simplified)"""
        mirrored = features.copy()
        # For production, implement proper mirroring
        return mirrored

# ============== Training ==============
def train_model(model, train_loader, val_features, val_scores):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    print(f"\n🔧 Using device: {device}")
    
    optimizer = optim.AdamW(model.parameters(), lr=Config.LEARNING_RATE, 
                           weight_decay=Config.WEIGHT_DECAY)
    criterion = nn.MSELoss()
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', 
                                                      factor=0.5, patience=5)
    
    val_features_tensor = torch.tensor(val_features, dtype=torch.float32).to(device)
    val_scores_tensor = torch.tensor(val_scores, dtype=torch.float32).to(device)
    
    best_val_loss = float('inf')
    patience_counter = 0
    
    os.makedirs(Config.CHECKPOINT_DIR, exist_ok=True)
    
    print(f"\n🏋️  Training on {len(train_loader.dataset)} positions")
    print(f"   Validation: {len(val_features)} positions")
    print(f"   Batch size: {Config.BATCH_SIZE}")
    print(f"   Epochs: {Config.EPOCHS}")
    print(f"   Early stopping patience: {Config.PATIENCE}")
    
    for epoch in range(Config.EPOCHS):
        model.train()
        train_loss = 0.0
        batch_count = 0
        
        for features, scores in train_loader:
            features = features.to(device)
            scores = scores.to(device)
            
            optimizer.zero_grad()
            outputs = model(features)
            loss = criterion(outputs, scores)
            loss.backward()
            
            torch.nn.utils.clip_grad_norm_(model.parameters(), Config.GRADIENT_CLIP)
            optimizer.step()
            
            train_loss += loss.item()
            batch_count += 1
        
        avg_train_loss = train_loss / batch_count
        
        model.eval()
        with torch.no_grad():
            val_outputs = model(val_features_tensor)
            val_loss = criterion(val_outputs, val_scores_tensor).item()
        
        scheduler.step(val_loss)
        
        # Print progress
        progress = (epoch + 1) / Config.EPOCHS * 100
        print(f"Epoch {epoch+1:3d}/{Config.EPOCHS} [{progress:5.1f}%] - "
              f"Train Loss: {avg_train_loss:.6f}, Val Loss: {val_loss:.6f}")
        
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), os.path.join(Config.CHECKPOINT_DIR, 'best_model.pt'))
            patience_counter = 0
            print(f"  ✅ New best model saved (loss: {val_loss:.6f})")
        else:
            patience_counter += 1
            if patience_counter >= Config.PATIENCE:
                print(f"  ⏹️  Early stopping at epoch {epoch+1}")
                break
    
    # Load best model
    best_model_path = os.path.join(Config.CHECKPOINT_DIR, 'best_model.pt')
    if os.path.exists(best_model_path):
        model.load_state_dict(torch.load(best_model_path))
        print(f"\n✅ Loaded best model from {best_model_path}")
    else:
        print(f"\n⚠️  Best model not found, using current model")
    
    return model

# ============== Verification ==============
def verify_export(filepath):
    """Verify exported weights file"""
    try:
        file_size = os.path.getsize(filepath)
        expected_params = (Config.NNUE_INPUT_DIM * Config.NNUE_H1 +
                          Config.NNUE_H1 +
                          Config.NNUE_H1 * Config.NNUE_H2 +
                          Config.NNUE_H2 +
                          Config.NNUE_H2 * Config.NNUE_H3 +
                          Config.NNUE_H3 +
                          Config.NNUE_H3 * Config.NNUE_OUT +
                          Config.NNUE_OUT)
        
        expected_bytes = expected_params * 4
        
        print(f"\n🔍 Verification:")
        print(f"  File: {filepath}")
        print(f"  Size: {file_size:,} bytes ({file_size/1024/1024:.2f} MB)")
        print(f"  Expected: {expected_bytes:,} bytes ({expected_bytes/1024/1024:.2f} MB)")
        
        if file_size == expected_bytes:
            print("  ✅ File size matches!")
            
            # Test read
            weights = np.fromfile(filepath, dtype=np.float32)
            print(f"  ✅ Successfully read {len(weights):,} floats")
            return True
        else:
            print(f"  ⚠️  File size mismatch!")
            return False
            
    except Exception as e:
        print(f"  ❌ Error verifying: {e}")
        return False

def verify_bias_export(filepath):
    """Verify exported bias file"""
    try:
        expected_params = Config.NNUE_H1 + Config.NNUE_H2 + Config.NNUE_H3 + Config.NNUE_OUT
        expected_bytes = expected_params * 4
        
        file_size = os.path.getsize(filepath)
        
        print(f"\n🔍 Bias file verification:")
        print(f"  File: {filepath}")
        print(f"  Size: {file_size:,} bytes ({file_size/1024/1024:.2f} MB)")
        print(f"  Expected: {expected_bytes:,} bytes ({expected_bytes/1024/1024:.2f} MB)")
        
        if file_size == expected_bytes:
            print("  ✅ Bias file size matches!")
            biases = np.fromfile(filepath, dtype=np.float32)
            print(f"  ✅ Successfully read {len(biases):,} floats")
            print(f"  Bias statistics: min={biases.min():.4f}, max={biases.max():.4f}, mean={biases.mean():.4f}")
            return True
        else:
            print(f"  ⚠️  Bias file size mismatch!")
            return False
            
    except Exception as e:
        print(f"  ❌ Error verifying bias file: {e}")
        return False

# ============== Main ==============
def main():
    print("=" * 80)
    print("NNUE Training Module - WASM Optimized")
    print(f"Network: {Config.NNUE_INPUT_DIM} -> {Config.NNUE_H1} -> {Config.NNUE_H2} -> {Config.NNUE_H3} -> 1")
    print("=" * 80)
    
    # Check if data file exists
    if not os.path.exists(Config.DATA_FILE):
        print(f"\n❌ Data file not found: {Config.DATA_FILE}")
        print("Please run data_generator.py first to generate training data.")
        return
    
    # Step 1: Load data
    print(f"\n📂 Loading data from {Config.DATA_FILE}...")
    try:
        dataset = NNUE_Dataset(Config.DATA_FILE)
    except Exception as e:
        print(f"❌ Error loading data: {e}")
        return
    
    if len(dataset) == 0:
        print("❌ No data loaded!")
        return
    
    # Step 2: Split data
    total = len(dataset)
    val_size = int(total * Config.VALIDATION_SPLIT)
    train_size = total - val_size
    
    indices = list(range(total))
    random.shuffle(indices)
    train_indices = indices[:train_size]
    val_indices = indices[train_size:]
    
    train_dataset = torch.utils.data.Subset(dataset, train_indices)
    val_dataset = torch.utils.data.Subset(dataset, val_indices)
    
    val_features = np.array([dataset.features[i] for i in val_indices])
    val_scores = np.array([dataset.scores[i] for i in val_indices])
    
    train_loader = DataLoader(train_dataset, batch_size=Config.BATCH_SIZE, 
                              shuffle=True, num_workers=0, pin_memory=True)
    
    print(f"\n📊 Data split:")
    print(f"  Total: {total:,} positions")
    print(f"  Training: {len(train_dataset):,} positions")
    print(f"  Validation: {len(val_dataset):,} positions")
    
    # Step 3: Create and train model
    print(f"\n🧠 Creating NNUE model...")
    model = NNUEProduction()
    total_params = sum(p.numel() for p in model.parameters())
    print(f"  Total parameters: {total_params:,}")
    print(f"  Layer sizes: {Config.NNUE_INPUT_DIM} -> {Config.NNUE_H1} -> {Config.NNUE_H2} -> {Config.NNUE_H3} -> 1")
    
    model = train_model(model, train_loader, val_features, val_scores)
    
    # Step 4: Export combined weights for WASM
    print(f"\n💾 Exporting combined weights...")
    model.export_weights_wasm(Config.WASM_WEIGHTS_FILE)
    
    # Step 5: Export bias file separately
    print(f"\n💾 Exporting bias file...")
    model.export_bias_file(Config.BIAS_FILE)
    
    # Step 6: Export separate layer files (optional)
    print(f"\n💾 Exporting separate layer files...")
    model.export_weights_separate()
    
    # Step 7: Save PyTorch model
    torch.save(model.state_dict(), Config.MODEL_FILE)
    print(f"\n💾 Saved PyTorch model to {Config.MODEL_FILE}")
    
    # Step 8: Verify exports
    print(f"\n🔍 Verifying exports...")
    wasm_ok = verify_export(Config.WASM_WEIGHTS_FILE)
    bias_ok = verify_bias_export(Config.BIAS_FILE)
    
    # Step 9: Summary
    print("\n" + "=" * 80)
    print("✅ Training complete!")
    print("=" * 80)
    print("Exported files:")
    print(f"  📦 Combined weights: {Config.WASM_WEIGHTS_FILE} {'✅' if wasm_ok else '❌'}")
    print(f"  📦 Bias file: {Config.BIAS_FILE} {'✅' if bias_ok else '❌'}")
    print(f"  📦 PyTorch model: {Config.MODEL_FILE}")
    print(f"  📁 Checkpoints: {Config.CHECKPOINT_DIR}/")
    print(f"  📁 Separate layers: weights/")
    print("=" * 80)
    
    # Print usage instructions
    print("\n📖 WASM Usage:")
    print("  For combined weights (nnue_weights_wasm.bin):")
    print("    - Load entire file as float32 array")
    print("    - Order: w1, b1, w2, b2, w3, b3, w4, b4")
    print("  For separate bias file (nnue_bias.bin):")
    print("    - Load entire file as float32 array")
    print("    - Order: b1, b2, b3, b4")
    print("  For separate layer files (weights/):")
    print("    - Each file contains one layer's weights or biases")
    print("=" * 80)

if __name__ == "__main__":
    main()